import React, { useEffect } from 'react';
import { useAuth } from './contexts/AuthContext';
import { db } from './firebase';
import { collection, query, getDocs, writeBatch, doc } from 'firebase/firestore';

export const MigrationExecutor = () => {
  const { user } = useAuth();
  
  useEffect(() => {
    if (!user) return;
    if (localStorage.getItem('pratik_migration_done')) return;
    
    const run = async () => {
      try {
        console.log("Starting Pratik Migration...");
        // 1. Get Pratik Shah's ID
        const usersSnap = await getDocs(collection(db, 'jpc_users'));
        let pratikId = null;
        const usersList: any[] = [];
        usersSnap.forEach(snap => {
          const u = snap.data();
          usersList.push({ id: snap.id, ...u });
          if ((u.display_name && u.display_name.toLowerCase().includes('pratik')) || u.username === 'pratik.shah') {
            pratikId = snap.id;
          }
        });
        
        if (!pratikId) {
          console.error("Could not find Pratik Shah ID.");
          return;
        }
        
        console.log("Found Pratik ID", pratikId);
        
        // 2. Fetch leads
        const candsSnap = await getDocs(collection(db, 'jpc_candidates'));
        const batch = writeBatch(db);
        let updatedCount = 0;
        
        candsSnap.forEach(snap => {
          const cand = snap.data();
          const source = (cand.lead_source || '').toLowerCase();
          
          // identify the imported leads
          const isImported = source.includes('custom import') || source.includes('self leads') || source.includes('khushi') || source.includes('bharat') || source.includes('ai cold') || (cand.notes && cand.notes.includes('Imported Follow up'));
          
          if (isImported && cand.assigned_sales !== pratikId) {
            const ref = doc(db, 'jpc_candidates', snap.id);
            
            // Re-map lead generated by
            let newLeadGen = cand.lead_generated_by;
            if (source.includes('self')) {
              newLeadGen = null; // no lead generation person
            } else {
              // Try to find the person based on text (Khushi, Bharat, etc.)
              const foundUser = usersList.find(u => source.includes(u.display_name?.split(' ')[0].toLowerCase()) || source.includes(u.username?.split('.')[0].toLowerCase()));
              if (foundUser) {
                newLeadGen = foundUser.id;
              }
            }
            
            batch.update(ref, { 
              assigned_sales: pratikId,
              lead_generated_by: newLeadGen
            });
            updatedCount++;
          }
        });
        
        if (updatedCount > 0) {
          await batch.commit();
          console.log(`Successfully migrated ${updatedCount} candidates to Pratik!`);
          alert(`Successfully updated and transferred ${updatedCount} imported candidates to Pratik Shah!`);
        } else {
          console.log("No imported candidates found to migrate.");
        }
        
        localStorage.setItem('pratik_migration_done', 'true');
      } catch (err) {
        console.error("Migration failed:", err);
      }
    };
    
    run();
  }, [user]);
  
  return null;
};
